### PR TITLE
PR for issue #12 collectFollowSets works incorrectly when ...

### PR DESCRIPTION
**Pull request by alessiostalla**
This tracks already-seen states with a stack rather than an always-growing set. 

The Expr grammar in the test has been modified to cause the reported issue.

I've had to change the expected outcome of several of the C++ grammar tests but as far as I understand they're all still valid with respect to the grammar, they're only finding different paths to the same rule (which prompts another issue).

### CODE REVIEW

**Comment by mike-lischke** [comment]
The different paths make me a bit nervous, but it should be ok, if the new paths are correct according to the grammar. Still, I want to check that in detail later, before merging your patch.

**Comment by alessiostalla** [comment]
Sure, I think more testing would be good, but I couldn't find a way to debug the test suite and thoroughly look into the differences.

**Comment by mike-lischke** [comment]
btw. please sign the contributors.txt file.

**Comment by alessiostalla** [comment]
Done. BTW this also seems to render translateRulesTopDown true/false irrelevant, at least in the outcome, I didn't look into time/performance.

**Comment by alessiostalla** [comment]
@mike-lischke any news? Do you need/want me to do something, such as write additional tests, compare before/after test results, ...?

**Comment by mike-lischke** [comment]
Sorry, pretty busy times. I need to found a few hours to come back to this project and your patch. It's on my list, however.

**Comment by alessiostalla** [comment]
No problem :) just let me know if I can be of any help as I do have some time to dedicate to this.

**Review by mike-lischke — APPROVED** [review]

**Comment by mike-lischke** [comment]
OK, this is merged. Thanks for the PR!

**Comment by alessiostalla** [comment]
Thanks a lot!

**Pull request merged**
